# =============================================================================
#  17_objective2_indian_cohort.R
#
#  Validation of the computational findings in an independent Indian cohort of
#  104 invasive ductal carcinomas, assayed by methylation-specific PCR for five
#  genes, with receptor status and clinicopathological data.
#
#  PREDICTIONS TESTED, generated by the analysis in scripts 01 to 15
#    (i)   GSTP1 promoter methylation is less frequent in receptor-negative
#          than in receptor-positive disease
#    (ii)  It is lowest, or absent, in triple-negative disease
#    (iii) The deficit is gene-specific and not a reflection of a general
#          difference in promoter methylation between subtypes
#    (iv)  Methylation is associated with established prognostic indicators
#
#  DESIGN NOTE
#    This cohort has no survival or treatment-response data. Prognostic
#    significance is assessed as association with established prognostic
#    indicators, not with outcome. That limitation is stated in the output and
#    must be stated in the manuscript.
#
#  INPUT
#    data/obj2_indian_cohort.csv, columns as documented in the repository
#    README. Patient-level data are not deposited; see the data availability
#    statement.
# =============================================================================

DATA <- "data/obj2_indian_cohort.csv"
OUT  <- "objective2"
dir.create(OUT, showWarnings = FALSE, recursive = TRUE)

if (!requireNamespace("ggplot2", quietly = TRUE)) install.packages("ggplot2")
suppressPackageStartupMessages(library(ggplot2))

if (!file.exists(DATA))
  stop("Patient data not found. This script requires the Objective 2 cohort,\n",
       "which is not publicly deposited. See the data availability statement.")

d <- read.csv(DATA, stringsAsFactors = FALSE)
GENES <- c("GSTP1","HIC1","CDH1","p16","BRCA1")

hdr <- function(t) cat("\n", strrep("=", 70), "\n", t, "\n",
                       strrep("=", 70), "\n", sep = "")


# =============================================================================
# 1. DERIVED VARIABLES
# =============================================================================
d$grade_hi <- ifelse(d$grade %in% c("III","IV"), "high",
              ifelse(d$grade %in% c("I","II"),  "low", NA))

# Nodal status from the TNM string
d$N <- ifelse(grepl("N\\d", d$TNM), sub(".*?N(\\d).*", "\\1", d$TNM), NA)
d$node_pos <- ifelse(!is.na(d$N) & d$N != "0", "positive",
              ifelse(!is.na(d$N) & d$N == "0", "negative", NA))

# Any receptor value that is not + or - is uninterpretable and set to NA
for (v in c("ER","PR","HER2")) {
  d[[v]] <- trimws(d[[v]])
  n_bad <- sum(!d[[v]] %in% c("+","-"))
  if (n_bad) cat("Note:", n_bad, "uninterpretable", v, "value(s) set to NA\n")
  d[[v]][!d[[v]] %in% c("+","-")] <- NA
}

d$TN <- ifelse(d$ER == "-" & d$PR == "-" & d$HER2 == "-", "triple-negative",
        ifelse(!is.na(d$ER) & !is.na(d$HER2), "non-triple-negative", NA))

for (g in GENES) d[[paste0(g,"_meth")]] <- d[[paste0(g,"_M")]] == "+"

cat("\nCases:", nrow(d), "\n")
print(table(d$cohort))


# =============================================================================
# 2. METHYLATION FREQUENCY
# =============================================================================
hdr("Promoter methylation frequency with exact confidence intervals")

freq <- do.call(rbind, lapply(GENES, function(g) {
  v <- d[[paste0(g,"_meth")]]
  k <- sum(v, na.rm = TRUE); n <- sum(!is.na(v))
  ci <- binom.test(k, n)$conf.int
  data.frame(gene = g, methylated = k, total = n,
             percent = round(100*k/n, 1),
             ci_low = round(100*ci[1], 1), ci_high = round(100*ci[2], 1))
}))
print(freq, row.names = FALSE)
write.csv(freq, file.path(OUT, "methylation_frequency.csv"), row.names = FALSE)

cat("\nThese are methylation-specific PCR frequencies and are not directly\n")
cat("comparable with array-derived figures; the two interrogate different CpG\n")
cat("positions and apply different thresholds.\n")


# =============================================================================
# 3. TEST FUNCTION
# =============================================================================
test2 <- function(dat, var, gene = "GSTP1") {
  v <- dat[[paste0(gene,"_meth")]]; f <- dat[[var]]
  ok <- !is.na(v) & !is.na(f); v <- v[ok]; f <- factor(f[ok])
  if (nlevels(f) != 2) return(NULL)
  tb <- table(f, v)
  if (!all(c("FALSE","TRUE") %in% colnames(tb))) return(NULL)
  tb <- tb[, c("FALSE","TRUE"), drop = FALSE]
  ft <- fisher.test(tb[, c(2,1)]); lv <- levels(f)
  data.frame(gene = gene, factor = var,
             group1 = sprintf("%s %d/%d (%.1f%%)", lv[1], tb[1,2],
                              sum(tb[1,]), 100*tb[1,2]/sum(tb[1,])),
             group2 = sprintf("%s %d/%d (%.1f%%)", lv[2], tb[2,2],
                              sum(tb[2,]), 100*tb[2,2]/sum(tb[2,])),
             OR = round(unname(ft$estimate), 2),
             p  = signif(ft$p.value, 3), stringsAsFactors = FALSE)
}


# =============================================================================
# 4. PRIMARY HYPOTHESIS
# =============================================================================
hdr("GSTP1 methylation by receptor status")

for (v in c("ER","PR","TN")) {
  r <- test2(d, v); if (!is.null(r)) print(r, row.names = FALSE)
}

cat("\nBy cohort, independent replication:\n")
for (co in sort(unique(d$cohort))) {
  r <- test2(d[d$cohort == co, ], "ER")
  if (!is.null(r)) cat(sprintf("  Cohort %s: %s vs %s, OR %.2f, p %.3f\n",
                               co, r$group1, r$group2, r$OR, r$p))
}

tn <- d[d$TN == "triple-negative" & !is.na(d$TN), ]
k <- sum(tn$GSTP1_meth, na.rm = TRUE); n <- sum(!is.na(tn$GSTP1_meth))
ci <- binom.test(k, n)$conf.int
cat(sprintf("\nTriple-negative: %d/%d = %.1f%% (95%% CI %.1f-%.1f)\n",
            k, n, 100*k/n, 100*ci[1], 100*ci[2]))
if (k == 0) cat("A zero count is reported with its exact upper confidence bound\n",
                "rather than as a point estimate.\n", sep = "")


# =============================================================================
# 5. THE SPECIFICITY ARGUMENT
# =============================================================================
hdr("All five genes by triple-negative status")
cat("If triple-negative tumours were globally hypomethylated, all five genes\n")
cat("would decline together. This tests whether the deficit is gene-specific.\n\n")

spec <- do.call(rbind, lapply(GENES, function(g) test2(d, "TN", g)))
print(spec, row.names = FALSE)
write.csv(spec, file.path(OUT, "specificity_by_TN.csv"), row.names = FALSE)


# =============================================================================
# 6. CLINICOPATHOLOGICAL ASSOCIATIONS
# =============================================================================
hdr("Methylation and established prognostic indicators")
cat("No survival data accompany this cohort. Prognostic significance is\n")
cat("assessed as association with prognostic indicators, not with outcome.\n")

FACTORS <- c("grade_hi","node_pos","ER","PR","HER2","TN")
res <- do.call(rbind, lapply(FACTORS, function(v)
  do.call(rbind, lapply(GENES, function(g) test2(d, v, g)))))
res$p_adj <- signif(p.adjust(res$p, "BH"), 3)
res <- res[order(res$p), ]
write.csv(res, file.path(OUT, "clinicopathological_associations.csv"), row.names = FALSE)

cat("\nNominally significant (p < 0.05, uncorrected):\n")
print(res[res$p < 0.05, ], row.names = FALSE)

cat(sprintf("\nTests: %d | nominal hits: %d | expected by chance: %.1f\n",
            nrow(res), sum(res$p < 0.05), 0.05*nrow(res)))
cat("\nBy gene:\n"); print(table(factor(res$gene[res$p < 0.05], levels = GENES)))
if (all(res$p_adj >= 0.05))
  cat("\nNo association survives correction across all tests. Report as\n",
      "exploratory. Note that the overall number of nominal hits is close to\n",
      "chance expectation, but their concentration in one gene is not.\n", sep = "")


# =============================================================================
# 7. FIGURE
# =============================================================================
pd <- do.call(rbind, lapply(GENES, function(g)
  do.call(rbind, lapply(c("non-triple-negative","triple-negative"), function(t) {
    s <- d[d$TN == t & !is.na(d$TN), ]
    k <- sum(s[[paste0(g,"_meth")]], na.rm = TRUE)
    n <- sum(!is.na(s[[paste0(g,"_meth")]]))
    ci <- binom.test(k, n)$conf.int
    data.frame(gene = g, group = t, pct = 100*k/n,
               lo = 100*ci[1], hi = 100*ci[2], lab = paste0(k,"/",n))
  }))))
pd$gene <- factor(pd$gene, levels = GENES)

p <- ggplot(pd, aes(gene, pct, fill = group)) +
  geom_col(position = position_dodge(0.8), width = 0.7) +
  geom_errorbar(aes(ymin = lo, ymax = hi), position = position_dodge(0.8),
                width = 0.2, linewidth = 0.4) +
  geom_text(aes(y = hi + 3, label = lab), position = position_dodge(0.8), size = 2.8) +
  scale_fill_manual(values = c("non-triple-negative" = "#2E86AB",
                               "triple-negative" = "#C0392B"), name = NULL) +
  labs(x = NULL, y = "Promoter methylation (%)",
       title = "Promoter methylation by triple-negative status",
       subtitle = sprintf("Indian breast cancer cohort, n = %d; exact 95%% confidence intervals",
                          nrow(d))) +
  theme_bw(base_size = 11) + theme(legend.position = "top")

ggsave(file.path(OUT, "methylation_by_TN.png"), p, width = 8, height = 5,
       dpi = 300, bg = "white")
ggsave(file.path(OUT, "methylation_by_TN.tiff"), p, width = 8, height = 5,
       dpi = 300, bg = "white", compression = "lzw")

hdr("DONE")
cat("Written to", normalizePath(OUT), "\n")

writeLines(c(paste("Run:", Sys.time()),
  "Objective 2, Indian cohort, n = 104.",
  "Fisher exact tests; Benjamini-Hochberg correction across all comparisons.",
  "No survival or treatment-response data available.",
  "", capture.output(sessionInfo())), file.path(OUT, "provenance.txt"))
